version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: vaibes_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: vaibes_db
      MYSQL_USER: vaibes_user
      MYSQL_PASSWORD: vaibes_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: